### ISSUE TITLE
Artisan.yml Parser cannot parse matrix entries with one value

### ISSUE THREAD

**Issue by SethMichaelLarson** [SethMichaelLarson/artisan-ci#92]
Parser should be able to handle static entries within a matrix.
```yaml
jobs:
  - name: 'tests-virtualbox'
    script: '.artisan/tests.py'
    duration: 20
    env:  # Set an environment variable so the tests for VirtualBox can run.
      - 'VIRTUALBOX=true'
    labels:
      matrix:
        platform:
          - 'ubuntu>=14.04'
          - 'windows>=10'
        python:
          - 'cpython==2.7'
          - 'cpython==3.5'
          - 'cpython==3.6'
        virtualbox: '>=5.1.14'  # This is the entry that cannot parse correctly.
```
